[package]
name = "rumatrix"
version = "0.1.0"
edition = "2021"
authors = ["Piotr Czarny"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "2.0"
rand = "0.8"
ctrlc = "3.2"
clap = { version = "4.0", features = ["derive"] }
